# Generated by Django 3.2.8 on 2021-10-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkcreator',
            name='shorted_url',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
