# Generated by Django 3.2.8 on 2021-10-24 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0002_alter_shortlinkcreator_shorted_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkcreator',
            name='long_url',
            field=models.URLField(validators=[django.core.validators.URLValidator(['http', 'https'])]),
        ),
    ]
