# Generated by Django 3.2.8 on 2021-10-24 14:28

from django.db import migrations, models
import short_link_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0003_alter_shortlinkcreator_long_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkcreator',
            name='expiration_time',
            field=models.DateTimeField(default=short_link_app.utils.expire_at, validators=[short_link_app.utils.validate_expire_time]),
        ),
    ]
