# Generated by Django 3.2.8 on 2021-10-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0004_alter_shortlinkcreator_expiration_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlinkcreator',
            old_name='long_url',
            new_name='original_url',
        ),
        migrations.RenameField(
            model_name='shortlinkcreator',
            old_name='times_redirected',
            new_name='redirected_times',
        ),
        migrations.RemoveField(
            model_name='shortlinkcreator',
            name='shorted_url',
        ),
        migrations.AddField(
            model_name='shortlinkcreator',
            name='is_shorten_url_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortlinkcreator',
            name='shorten_url',
            field=models.CharField(blank=True, max_length=18, unique=True),
        ),
    ]
