# Generated by Django 3.2.8 on 2021-10-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0005_auto_20211024_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkcreator',
            name='is_shorten_url_private',
            field=models.BooleanField(default=False, verbose_name='Private URL?'),
        ),
    ]
