# Generated by Django 3.2.8 on 2021-10-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0006_alter_shortlinkcreator_is_shorten_url_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlinkcreator',
            old_name='shorten_url',
            new_name='shorten_link',
        ),
    ]
