# Generated by Django 3.2.8 on 2021-10-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0007_rename_shorten_url_shortlinkcreator_shorten_link'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shortlinkcreator',
            constraint=models.CheckConstraint(check=models.Q(('shorten_link__length__gte', 8)), name='short_link_app_shortlinkcreator_shorten_link_length'),
        ),
    ]
