# Generated by Django 3.2.8 on 2021-10-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0008_shortlinkcreator_short_link_app_shortlinkcreator_shorten_link_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shortlinkcreator',
            name='short_link_app_shortlinkcreator_shorten_link_length',
        ),
        migrations.AddConstraint(
            model_name='shortlinkcreator',
            constraint=models.CheckConstraint(check=models.Q(('shorten_link__length__gte', 8)), name='Check constraints for shorten_link field that must be gte 8'),
        ),
    ]
