# Generated by Django 3.2.8 on 2021-10-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0009_auto_20211025_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlinkcreator',
            options={'ordering': ['-created_time']},
        ),
    ]
