# Generated by Django 3.2.8 on 2021-10-25 09:10

from django.db import migrations, models
import short_link_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0010_alter_shortlinkcreator_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkcreator',
            name='shorten_link',
            field=models.CharField(
                blank=True, default=short_link_app.defaults.generate_token, max_length=18, unique=True),
        ),
    ]
