# Generated by Django 3.2.8 on 2021-10-28 13:39

import django.core.validators
from django.db import migrations, models
import short_link_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0014_alter_shortlinkcreator_shorten_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlinkcreator',
            name='shorten_link',
        ),
        migrations.AddField(
            model_name='shortlinkcreator',
            name='token',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[
                                   django.core.validators.RegexValidator('[\\w-]{8,18}'), short_link_app.validators.check_token_min_length]),
        ),
        migrations.AlterField(
            model_name='shortlinkcreator',
            name='original_url',
            field=models.URLField(max_length=1024, validators=[django.core.validators.URLValidator(['http', 'https'])]),
        ),
    ]
