# Generated by Django 3.2.8 on 2021-10-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0016_alter_shortlinkcreator_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlinkcreator',
            old_name='token',
            new_name='token_url',
        ),
    ]
