# Generated by Django 3.2.8 on 2021-10-28 13:55

import django.core.validators
from django.db import migrations, models
import short_link_app.defaults
import short_link_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0017_rename_token_shortlinkcreator_token_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkcreator',
            name='token_url',
            field=models.CharField(default=short_link_app.defaults.generate_token, max_length=18, unique=True, validators=[
                                   django.core.validators.RegexValidator('[\\w-]{8,18}'), short_link_app.validators.check_token_min_length], verbose_name='back-half'),
        ),
    ]
