# Generated by Django 3.2.8 on 2021-10-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0019_rename_token_url_shortlinkcreator_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlinkcreator',
            old_name='redirected_times',
            new_name='times_of_redirected',
        ),
    ]
