# Generated by Django 3.2.8 on 2021-10-28 14:06

import django.core.validators
from django.db import migrations, models
import short_link_app.defaults
import short_link_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_app', '0021_rename_is_shorten_url_private_shortlinkcreator_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkcreator',
            name='token',
            field=models.CharField(default=short_link_app.defaults.generate_token, max_length=18, unique=True, validators=[
                                   django.core.validators.RegexValidator('[\\w-]{8,18}'), short_link_app.validators.check_token_min_length]),
        ),
    ]
