# Generated by Django 3.2.8 on 2021-11-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userotpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotpcode',
            name='user_secret_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
