# Generated by Django 3.2.8 on 2021-11-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211101_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userotpcode',
            old_name='user_secret_key',
            new_name='secret_key',
        ),
    ]
