# Generated by Django 3.2.8 on 2021-11-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_usersecretkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotpcode',
            name='otp_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userotpcode',
            name='secret_key',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
